language: java

sudo: false

addons:
  hosts:
  - db

env:
  global:
    # Ensure Google Cloud SDK doesn't prompt for installing.
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

services:
- docker


install:
# Build database image.
- docker build -t database db/.
# Run the database image.
- docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
# Build and install the application.
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
